dist: trusty
sudo: required
language: node_js
cache: npm
git:
  depth: 5
node_js:
  - "10"
  - "8"
  - "6"
before_install:
  - sudo sysctl fs.inotify.max_user_watches=524288
  - npm i -g greenkeeper-lockfile@1 rimraf
before_script:
  # - greenkeeper-lockfile-update
script:
  - npm test
after_script:
  # - greenkeeper-lockfile-upload
