language: node_js

env:
  - TS_JEST_E2E_WORKDIR=/tmp/ts-jest-e2e-workdir

cache:
  npm: true
  directories:
    - /tmp/ts-jest-e2e-workdir/__templates__

node_js:
  - "10"
  - "8"
  - "6"

before_install:
  # https://github.com/scikit-learn/scikit-learn/issues/10927
  - |
      set -e
      # fail loudly when force-pushed, that is why there is the `|| 'dummy.js'` part
      MODIFIED_FILES=$(git diff --name-only $TRAVIS_COMMIT_RANGE || echo 'dummy.js')
      # waiting for native solution https://github.com/travis-ci/travis-ci/issues/6301
      if ! echo ${MODIFIED_FILES} | grep -qvE '(\.md$)|(^docs)/'; then
        echo "Only docs were updated, stopping build process."
        exit
      fi
  - dpkg --compare-versions `npm -v` ge 5.8 || npm i -g npm@latest

script:
  - npm run clean -- --when-ci-commit-message
  - npm run test -- --coverage
