language: node_js

env:
  - TS_JEST_E2E_WORKDIR=/tmp/ts-jest-e2e-workdir

cache:
  npm: true
  directories:
    - /tmp/ts-jest-e2e-workdir/__templates__

node_js:
  - "10"
  - "8"
  - "6"

before_install:
  - dpkg --compare-versions `npm -v` ge 5.8 || npm i -g npm@latest

script:
  - npm run clean -- --when-ci-commit-message
  - npm run test -- --coverage
