dist: trusty
sudo: required
language: node_js

env:
  - TS_JEST_E2E_WORKDIR=/tmp/ts-jest-e2e-workdir

cache:
  npm: true
  directories:
    - /tmp/ts-jest-e2e-workdir

node_js:
  - "10"
  - "8"
  - "6"

script:
  - npm run test
